### ISSUE TITLE
Make it no_std compatible?

### ISSUE THREAD

**Issue by hongquan** [Artem-Romanenia/o2o#14]
I want to use o2o in an embedded project, but not able yet because `o2o` pulls `std` dependency.
In terms of feature, _o2o_ generates code for `From` traits, which can totally work with `no-std`. But it is just that the expanded code refers to `std`, it cannot be compiled in `no-std` environment.
I propose to import `From` trait from [core](https://doc.rust-lang.org/beta/core/index.html)::[convert](https://doc.rust-lang.org/beta/core/convert/index.html)::[From](https://doc.rust-lang.org/beta/core/convert/trait.From.html#), to make code compilable in `no-std`.

**Comment by Artem-Romanenia** [comment]
Hi, thank you for showing interest in my project!

I'm completely on board with this proposition, but it will take me some figuring out what is the best way to do it. I feel like just straight changing the type of trait o2o implements may affect existing users? I would like to do it without making it a breaking change.. I think of introducing features, like 'std' (which would be default) and 'nostd' (which would have to be opted-in), and then using something like cfg-if crate to choose between `std::` vs `core::`

Anyways, this is now the only thing in my to-do list, so it should be coming sooner than later)

Btw, if you have any other thoughts/suggestions, that would be very welcome!

**Comment by hongquan** [comment]
You can define `std` feature, which would be activated by default (to not break existing users). If someone wants to use in `no-std` environment, just add `o2o` as dependency via:

```sh
cargo add o2o --no-default-features
```

**Comment by hongquan** [comment]
I remember that, even if you forcily change `std::convert::From` to `core::convert::From`, it won't affect existing users. Because `std::convert::From` is just re-exported from `core`.

**Comment by Artem-Romanenia** [comment]
Hi, thanks for comments! I decided not to bother with introducing features and just change to `::core::convert::...`. I have one more question for you however. In o2o, apart from using rust's `::core::convert::...` I also define my own traits `o2o::traits::(Try)IntoExisting`. So, if you or somebody else ever wanted to use them in a no_std project, does o2o also needs to be defined as no_std? Intuitively I thought yes, but I created a test no_std project and had no problems using o2o published without no_std flag.

P.S. If you want, you can now use o2o v0.4.9-alpha.1 to see if it fits your needs

**Comment by hongquan** [comment]
I now added o2o as:

```toml
o2o = { version = "0.4.9-alpha.1", default-features = false }
```

But when building, cargo tried to build `proc-macro2` with no_std compiler.

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not support the standard library
  = note: `std` is required by `proc_macro2` because it does not declare `#![no_std]`
```

cargo may make mistake here, but I don't know how to adjust it.

**Comment by Artem-Romanenia** [comment]
Ok, I think I figured this out. The problem was that in case of no_std project you need to use `o2o-macros` crate, which contains the main proc macro, not the `o2o` which re-exports the proc macro.

I updated some code, and now, to have 90% of the functionality, you just need this in you cargo.toml:

```
[dependencies]
o2o-macros = "0.4.9-alpha.2"
```

For 100% of the functionality, you need this:

```
[dependencies]
o2o-macros = "0.4.9-alpha.2"
o2o = { version = "0.4.9-alpha.3", default-features = false }
```

In this mode, `o2o` will merely contain traits `o2o::traits::IntoExisting` and `o2o::traits::TryIntoExisting` that `o2o-macro` can implement in certain configurations. If you don't need IntoExisting, that just use the first option.

**Comment by Artem-Romanenia** [comment]
These are current [instructions](https://github.com/Artem-Romanenia/o2o?tab=readme-ov-file#no_std) how to use o2o in no_std project.

Thanks for opening this issue! Please let me know if you have any other problems or ideas.

**Comment by hongquan** [comment]
Thank you.
