### ISSUE TITLE
use std::result::Result

### ISSUE THREAD

**Issue by shmy** [Artem-Romanenia/o2o#22]
Hi, this is a great crate, but I had a issue, if my scope custom a Result type, the owned_try_into don't work 

<img width="705" alt="image" src="https://github.com/user-attachments/assets/34deec97-4a00-40f2-ab88-dd76ed624b48">

**Comment by Artem-Romanenia** [comment]
Hi, thanks for raising an issue! Please use version 0.4.11, I used `::core::result::Result` for no_std compatibility, but it's the same thing. Please let me know if you have any other issues!

**Comment by shmy** [comment]
Thank you
